version: '3'
services:
  competitive:
    build: ./competitiveness
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./competitiveness/src:/home/app/competitive/src
  express:
    build: ./backend
    ports:
      - '8080:8080'
